config/routes.rb
Places::Application.routes.draw do
  resources :places

end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :address, :city, :country, :description, :houseno, :latitude, :longitude, :rent, :street, :user
  acts_as_gmappable :process_geocoding => false
  geocoded_by :full_address
  
  after_save {update_column(:address, "#{houseno}, #{street}, #{city}, #{country}")}

  before_update {update_column(:address, "#{houseno}, #{street}, #{city}, #{country}")}

  after_validation :geocode

  def full_address
  	"#{houseno}, #{street}, #{city}, #{country}"
  end	

  def gmaps4rails_address
      "#{houseno}, #{street}, #{city}, #{country}"
  end

  def gmaps4rails_infowindow
    "<ul class='list-unstyled'>
    <li>Name: #{user}</li>
    <li>Rent: Rs. #{rent}</li>
    <li>Address: #{address}</li>
    </ul>"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json
  def index
    if params[:search].present?
      @places = Place.near(params[:search], 10, :order => :distance)
      @json = Place.near(params[:search], 10, :order => :distance)
    else
      @places = Place.all
      @json = Place.all
    end  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    @json = Place.all.to_gmaps4rails
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Places</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
<%= yield %>
</div>
<%= yield :scripts %>
</body>
</html>

app/views/places/_form.html.erb
<%= form_for @place, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :user,  :placeholder => "Your fullname",:class => 'number_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :rent, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :rent,  :placeholder => "Rent in INR",:class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :placeholder => "Brief Description", :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "Street address", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :houseno, :placeholder => "House no, Street name ", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Area/Locality", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :street,  :placeholder => "Street name/ Area", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :placeholder => "City", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :placeholder => "Country", :class => 'text_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-large' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                places_path, :class => 'btn btn-large' %>
  </div>
<% end %>

app/views/places/edit.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/places/index.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<%= form_tag places_path, :method => :get do %>
  <p>
    <%= submit_tag "Search Places Near", :name =>nil %>
    <%= text_field_tag :search, params[:search] %>
  </p>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user) %></th>
      <th><%= model_class.human_attribute_name(:rent) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:full_address) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.id, place_path(place) %></td>
        <td><%= link_to place.user, place_path(place) %></td>
        <td><%= place.rent %></td>
        <td><%= place.description %></td>
        <td><%= place.address%></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_place_path(place), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      place_path(place),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_place_path,
            :class => 'btn btn-large' %>

<h4> Places at a glance </h4>
<%= gmaps4rails(@json) %>

app/views/places/new.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/places/show.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name("Name") %>:</strong></dt>
  <dd><%= @place.user %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rent) %>:</strong></dt>
  <dd><%= @place.rent %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @place.description %></dd>
  <dt><strong><%= model_class.human_attribute_name("Street Address") %>:</strong></dt>
  <dd><%= @place.houseno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Area) %>:</strong></dt>
  <dd><%= @place.street %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @place.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @place.country %></dd>
</dl>

<hr>

<h4> Nearby Locations </h4>

  <ul>
  <%for place in @place.nearbys(10) %>
    <li><%= link_to place.address, place %> ( About <%= ((place.distance)*1.61).round(2) %> kms away) </li>
  <% end %>
</ul>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              places_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_place_path(@place), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              place_path(@place),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>